baseURL = 'https://flasa.si'
languageCode = 'en-us'
title = 'flasa.si'
theme = "shibui"

[params]
  author = "Jasa Jovan"
  email = "jasa@flasa.si"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 2

[caches]
  [caches.images]
    dir = ':cacheDir/images'